# Generated by generate_rankinfo.py; edit rankinfo.json instead.
tellraw @s ["",{"text":"==================== ","color":"yellow"},{"text":"Member","bold":true,"color":"#1C8EEF","click_event":{"action":"run_command","command":"/trigger rankinfo set 1"},"hover_event":{"action":"show_text","value":{"text":"[Click for entire list]","color":"gold"}}},{"text":" ====================","color":"yellow"}]

tellraw @s ["",{"text":"[Permissions from Previous Ranks]:","bold":true,"color":"white"},"\n",{"text":"All Basic Commands, /sit, :item: in chat, /gesture, /hat","color":"yellow"},"\n\n",{"text":"[New Permissions]:","bold":true,"color":"white"},"\n",{"text":"10 claims, 4 homes, /signedit, Basic Chat Coloring, /hug","color":"yellow"}]

tellraw @s {"text":"=================================================","color":"yellow"}

scoreboard players reset @s rankinfo
scoreboard players enable @s rankinfo
