#!/usr/bin/env python3
"""Generate the rankinfo mcfunction files from rankinfo.json.

Edit scripts/rankinfo/rankinfo.json, then run from the repository root:
    python3 scripts/rankinfo/generate_rankinfo.py

Use --check in CI to verify that generated files are current.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
TRIGGER_DIR = REPO_ROOT / "kilocraft/data/kilocraft/function/trigger"
CONFIG_PATH = Path(__file__).resolve().with_name("rankinfo.json")
OUTPUT_DIR = TRIGGER_DIR / "rankinfo"
GENERATED = "# Generated by generate_rankinfo.py; edit rankinfo.json instead.\n"
COLOR = re.compile(r"^(#[0-9a-fA-F]{6}|[a-z_]+)$")


def component(text: str, **style: Any) -> dict[str, Any]:
    return {"text": text, **style}


def compact(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def tellraw(target: str, value: Any) -> str:
    return f"tellraw {target} {compact(value)}"


def validate(config: dict[str, Any]) -> None:
    ranks = config.get("ranks")
    if not isinstance(ranks, list) or not ranks:
        raise ValueError("'ranks' must be a non-empty list")

    seen_files: set[str] = set()
    seen_triggers: set[int] = {1, 2}
    for rank in ranks:
        required = {"name", "file", "trigger", "color", "new_permissions"}
        missing = required - rank.keys()
        if missing:
            raise ValueError(f"rank is missing: {', '.join(sorted(missing))}")
        if not re.fullmatch(r"[a-z0-9_]+", rank["file"]):
            raise ValueError(f"invalid file name: {rank['file']!r}")
        if rank["file"] in seen_files:
            raise ValueError(f"duplicate file name: {rank['file']}")
        if rank["trigger"] in seen_triggers:
            raise ValueError(f"duplicate trigger: {rank['trigger']}")
        if not COLOR.fullmatch(rank["color"]):
            raise ValueError(f"invalid color for {rank['name']}: {rank['color']!r}")
        requirements = rank.get("requirements")
        if requirements is not None:
            for key in ("minutes", "votes"):
                if not isinstance(requirements.get(key), int) or requirements[key] < 0:
                    raise ValueError(f"{rank['name']}.{key} must be a non-negative integer")
        seen_files.add(rank["file"])
        seen_triggers.add(rank["trigger"])


def rank_link(rank: dict[str, Any], hover_prefix: str = "[Click for full list] ") -> dict[str, Any]:
    preview = rank.get("preview", rank["new_permissions"])
    return component(
        f"[{rank['name']}] - ",
        color=rank["color"],
        click_event={"action": "run_command", "command": f"/trigger rankinfo set {rank['trigger']}"},
        hover_event={"action": "show_text", "value": component(hover_prefix + preview, color="gold")},
    )


def detail_file(rank: dict[str, Any]) -> str:
    title = [
        "",
        component("==================== ", color="yellow"),
        component(
            rank["name"], bold=True, color=rank["color"],
            click_event={"action": "run_command", "command": "/trigger rankinfo set 1"},
            hover_event={"action": "show_text", "value": component("[Click for entire list]", color="gold")},
        ),
        component(" ====================", color="yellow"),
    ]
    body: list[Any] = [""]
    previous = rank.get("previous_permissions")
    if previous:
        body += [component("[Permissions from Previous Ranks]:", bold=True, color="white"), "\n",
                 component(previous, color="yellow"), "\n\n"]
    body += [component("[New Permissions]:", bold=True, color="white"), "\n",
             component(rank["new_permissions"], color="yellow")]
    return GENERATED + "\n".join([
        tellraw("@s", title), "", tellraw("@s", body), "",
        tellraw("@s", component("=================================================", color="yellow")), "",
        "scoreboard players reset @s rankinfo", "scoreboard players enable @s rankinfo", "",
    ])


def requirement_line(rank: dict[str, Any], minutes_met: bool, votes_met: bool) -> str:
    req = rank["requirements"]
    minute_range = f"{req['minutes']}.." if minutes_met else f"..{req['minutes'] - 1}"
    vote_range = f"{req['votes']}.." if votes_met else f"..{req['votes'] - 1}"
    target = f"@s[scores={{keutil_minutes={minute_range},kevote_total={vote_range}}}]"
    value: list[Any] = ["", rank_link(rank)]
    for amount, noun, objective, met in (
        (req["minutes"], "minutes", "keutil_minutes", minutes_met),
        (req["votes"], "votes", "kevote_total", votes_met),
    ):
        if noun == "votes":
            value.append(component(" and ", color="white"))
        value.append(component(
            f"[{amount} {noun}]", color="green" if met else "red",
            hover_event={"action": "show_text", "value": ["", component("You have ", color="white"),
                {"score": {"name": "@s", "objective": objective}, "color": "aqua"},
                component(f" {noun}", color="white")]},
        ))
    return tellraw(target, value)


def simple_rank_line(rank: dict[str, Any]) -> str:
    return tellraw("@s", ["", rank_link(rank), component(rank.get("description", "The default rank"), color=rank["color"])])


def paid_rank_lines(rank: dict[str, Any]) -> list[str]:
    permission = rank["paid_permission"]
    hide_condition = ""
    if hidden_permission := rank.get("hide_if_permission"):
        hide_condition = f" unless permission @s {hidden_permission}"
    preview = rank.get("preview", rank["new_permissions"])
    owned = (
        "tellmessage @s "
        f"<hover:'<gold>[Click for permission list] {preview}'>"
        f"<run_cmd:'/trigger rankinfo set {rank['trigger']}'>"
        f"<{rank['color']}>[{rank['name']}] - <reset>"
        f"<green>You have %{rank['expiry_placeholder']}% left"
    )
    available = tellraw(
        "@s",
        ["", rank_link(rank, "[Click for permission list] "), component(
            f"[{rank['price']}]", color="gold",
            click_event={"action": "run_command", "command": rank.get("store_command", "/store")},
            hover_event={"action": "show_text", "value": component("Click to visit store!", color="gold")},
        )],
    )
    return [f"execute if permission @s {permission}{hide_condition} run {owned}",
            f"execute unless permission @s {permission}{hide_condition} run {available}"]


def category_line(title: str, ranks: list[dict[str, Any]], bracket_color: str) -> str:
    value: list[Any] = ["", component(f"\n{title}: ", bold=True, color="white")]
    for index, rank in enumerate(ranks):
        if index:
            value.append(", ")
        hover = ["", component("[", color=bracket_color),
                 component(rank["short"], color=rank["color"]),
                 component("] ", color=bracket_color),
                 component(rank["description"], color=rank["color"])]
        value += [component("[", color=bracket_color), component(
            rank["name"], color=rank["color"],
            hover_event={"action": "show_text", "value": hover}), component("]", color=bracket_color)]
    return tellraw("@s", value)


def list_file(config: dict[str, Any]) -> str:
    lines = [GENERATED.rstrip(), tellraw("@s", ["", component("==================== ", color="yellow"),
        component("RankInfo", bold=True, color="gold"), component(" =====================", color="yellow")]),
        tellraw("@s", ["", component("HOVER", bold=True, color="gray"),
            component(" over ranks to preview permissions; click for the full list.", italic=True, color="gray"), "\n",
            component("[Click for basic permission list]", bold=True, color="white",
                click_event={"action": "run_command", "command": "/trigger rankinfo set 2"}), "\n\n",
            component("Playtime / Voting Ranks: ", bold=True, color="white")]), ""]
    paid: list[dict[str, Any]] = []
    for rank in config["ranks"]:
        if "paid_permission" in rank:
            paid.append(rank)
        elif "requirements" in rank:
            lines.append(f"#{rank['name']}")
            lines.extend(requirement_line(rank, m, v) for m, v in ((False, False), (True, False), (False, True), (True, True)))
            lines.append("")
        else:
            lines += [f"#{rank['name']}", simple_rank_line(rank), ""]
    if paid:
        lines.append(tellraw("@s", ["", "\n", component("Purchased Ranks: ", bold=True, color="white")]))
        for rank in paid:
            lines += [f"#{rank['name']}", *paid_rank_lines(rank), ""]
    for category in config.get("categories", []):
        lines.append(category_line(category["title"], category["ranks"], category["bracket_color"]))
    lines += ["", tellraw("@s", component("====================================================", color="yellow")), "",
              "scoreboard players reset @s rankinfo", "scoreboard players enable @s rankinfo", ""]
    return "\n".join(lines)


def dispatcher_file(config: dict[str, Any]) -> str:
    lines = [GENERATED.rstrip(),
             "execute if score @s rankinfo matches 1 run function kilocraft:trigger/rankinfo/list",
             "execute if score @s rankinfo matches 2 run function kilocraft:trigger/rankinfo/perms"]
    lines += [f"execute if score @s rankinfo matches {r['trigger']} run function kilocraft:trigger/rankinfo/{r['file']}"
              for r in config["ranks"]]
    return "\n".join(lines) + "\n"


def basic_permissions_file(config: dict[str, Any]) -> str:
    value: list[Any] = [""]
    for index, group in enumerate(config["basic_permissions"]):
        if index:
            value.append("\n\n")
        value += [component(f"[{group['name']}]:", bold=True, color="white"), "\n",
                  component(", ".join(group["permissions"]), color="yellow")]
    return GENERATED + "\n".join([
        tellraw("@s", ["", component("================ ", color="yellow"),
            component("Basic Commands", bold=True, color="gold"), component(" ================", color="yellow")]), "",
        tellraw("@s", value), "", tellraw("@s", component("=================================================", color="yellow")), "",
        "scoreboard players reset @s rankinfo", "scoreboard players enable @s rankinfo", "",
    ])


def outputs(config: dict[str, Any]) -> dict[Path, str]:
    result = {OUTPUT_DIR / "list.mcfunction": list_file(config),
              OUTPUT_DIR / "rankinfo.mcfunction": dispatcher_file(config),
              OUTPUT_DIR / "perms.mcfunction": basic_permissions_file(config)}
    result.update({OUTPUT_DIR / f"{rank['file']}.mcfunction": detail_file(rank) for rank in config["ranks"]})
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = parser.parse_args()
    try:
        config = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
        validate(config)
    except (OSError, json.JSONDecodeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    stale: list[Path] = []
    for path, content in outputs(config).items():
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        print(("out of date: " if args.check else "generated: ") + ", ".join(str(p.relative_to(REPO_ROOT)) for p in stale))
    return 1 if args.check and stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
